### ISSUE TITLE
Twitter is deactivating inactive accounts

### ISSUE THREAD

**Issue by philcryer** [restincode/restincode#130]
Sorry, this falls outside of the categories. Basically:

Twitter is deactivating inactive accounts, if a user doesn't login for 6 months, they reserve the right to deactivate the account, and make the username available again. Do we care? Do we just assume links to Twitter user accounts are going to be broken soon, and if they ever become working again they'll be to a totally different user? 

https://help.twitter.com/en/rules-and-policies/inactive-twitter-accounts

**Comment by attritionorg** [comment]
They reversed that decision specifically because of the deceased / memorial aspect, and are giving their plans more thought so as to respect such cases, while still freeing up account names.

https://twitter.com/TwitterSupport/status/1199777312054493184

Specifically:
https://twitter.com/TwitterSupport/status/1199777313300209664
We’ve heard you on the impact that this would have on the accounts of the deceased. This was a miss on our part. We will not be removing any inactive accounts until we create a new way for people to memorialize accounts.

**Comment by philcryer** [comment]
Excellent, I wasn't aware of that, thanks for the good news

**Comment by philcryer** [comment]
Since they changed their mind (for now) this is a moot issue. Closing
